### ISSUE TITLE
npx migrate ERROR!

### ISSUE THREAD

**Issue by JoseMariani** [rtenorioh/Press-Ticket#101]
He heco un fork y he creado una nueva migracion el problema es que me sale el error de sequalize de no poderme conectar a la base de datos, tambien me acaba de aparecer cuando he intentado ejecutar el UPdate y bajarme el codigo original del main? 

COMO HAGO PARA QUE FUNCIONE EL COMANDO: 
npx sequelize db:migrate 

YA he hasta creado el usuario full privilegios en el mariadb que esta en el contenedor que me crea el instalador automatico: 

CREATE USER 'myuser'@'localhost' IDENTIFIED BY 'umbralhosting';
grant all privileges on *.* to 'myuser'@'localhost' with grant option;

PERO me sigue saliendo = 

ERROR: Access denied for user 'myuser'@'172.17.0.1' (using password: YES) 

Obviamente ese es el ip del contenedor.. etc pero no entiendo cual es el problema al final de todo? hay alguien que me ayude?

**Comment by rtenorioh** [comment]
Ja tentou rodar esses comandos:

USE mysql;

UPDATE user SET plugin='mysql_native_password' WHERE User='root';

FLUSH PRIVILEGES;

exit;

service mysql restart

**Comment by JoseMariani** [comment]
Esto no resuelve le problema, ya que al hacer esta consulta: 

select User, plugin from mysql.user; 

Todos ya tienen configurado el plugin de autenticacion: mysql_native_password. 

Nota: Estas instalaciones de instancia se hicieron con el instalador automatico que coloca un contenedor docker con MariaDB, en caso de querer setear el plugin en MARIA DB se debe usar  ALTER USER. 

debe existir alguna solucion.. =(

**Comment by JoseMariani** [comment]
Hola yo nuevamente por aqui, con mis dudas, estoy haciendo el paso a paso de instalacion en un VPS tal cual esta en estaestoy siguiendo la guia que esta aqui en el repositorio de github... https://github.com/rtenorioh/Press-Ticket/blob/main/docs/INSTALL_VPS.md 

En el paso 9 esta lo de cambiarle el plugin de la interpretacion de contraseña como indicas.. 


**Todo bien yo sigo los pasos hasta llegar al paso 36: "npx sequelize db:migrate" 

Que es para que sequalize se ejecute y ejecute las migraciones, y me aparece ahora: 
que el usuario root@localhost no tiene acceso a la base. 

Sequelize CLI [Node: 16.20.0, CLI: 5.5.1, ORM: 5.22.5]

Loaded configuration file "dist/config/database.js".

ERROR: Access denied for user 'root'@'localhost' (using password: YES) 


Todos los pasos los he seguido a la perfeccion, el unico detalle en los pasos que no logro entender del todo son los pasos: 
22 -sudo usermod -aG mysql ${USER} 
23- su - ${USER} 

he copiado y pegado el comando tal cual aparece con "${USER}, no se si eso tenga que ver, en algo que este influyendo para que el usuario se conecte a la DB. 

Lo que creo es que hay algo que no esta estableciendo las variables de entorno. 

Nose si tenga que ver, pero el paso 41 tiene que ver con el estableciminto de variables en PM2, ye l apso 41 esta despues del 
paso 36 no se si tenga que ver, ya que como hace sequalize para saber la variable de entorno si no esta instanciada o definida con pm2? o si me pueden dar una pista de que puedo estar haciendo mal.

**Comment by JoseMariani** [comment]
He resuelto creando un usuario en la base de datos distinto de root, y dandole los privilegios en todas las databases. 

Luego tuve e problema de GateWay lo he resuelto aplicando una regla al firewall en linux: 
ufw allow NUMBER PORT y rieniciando nginx y los nodejs por p2m. 

-Nuevo Reto: 
Cuando voy a crear una nueva conexion ya dentro del frontend por el UI, Se queda cargando la nueva conexion y no me genera el QR, revisando la consola me encuentro con esto: 

websocket.js:203 WebSocket connection to 'wss://apiw.mybackendURL.com/socket.io/?EIO=4&transport=websocket&sid=mant2yROcRtTIozTAAAy' failed: WebSocket is closed before the connection is established.
 
 Alguna idea?
