### ISSUE TITLE
GPT ERROR

### ISSUE THREAD

**Issue by codsec** [rtenorioh/Press-Ticket#102]
preenchi ambos os campos corretamentas mas ainda sim recebo a msg de erro dizendo que não tenho api...

**Comment by rtenorioh** [comment]
vc tem creditos? pois se nao tiver creditos não conseguirá usa a integração

**Comment by codsec** [comment]
> vc tem creditos? pois se nao tiver creditos não conseguirá usa a integração

Tenho sim, 30$ usd disponiveis para uso

**Comment by codsec** [comment]
@rtenorioh existe alguma configuração além do id company e apikey? pois ambos estão corretos e tenho creditos

**Comment by codsec** [comment]
![image](https://github.com/rtenorioh/Press-Ticket/assets/44205014/18ebbcd8-5298-4a98-bf20-069fc07f0573)

**Comment by codsec** [comment]
@rtenorioh ??????

**Comment by rtenorioh** [comment]
estranho, pois tanto na minha versão de teste quento em minha versao em produção esta tudo normal, e só precisa inserir suas credenciais para funcionamento

**Comment by codsec** [comment]
> estranho, pois tanto na minha versão de teste quento em minha versao em produção esta tudo normal, e só precisa inserir suas credenciais para funcionamento

Infelizmente não está funcionando, um amigo testou com a dele tbm e nada, da o msm erro
