### ISSUE TITLE
Problema ao conectar ao Whatsapp

### ISSUE THREAD

**Issue by sergiobaiao** [rtenorioh/Press-Ticket#107]
Ola,

Instalei o pressticket em minha vm na Oracle, tudo conforme o passo-a-passo, subiu frontend e backend ok.

Porem, na hora de adicionar a conexão, fica girando a imagem de status e nada acontece. No dev console aparece a seguinte imagem:

![Screenshot 2023-05-22 151657](https://github.com/rtenorioh/Press-Ticket/assets/28034970/3c045a47-4cac-4dee-acfe-9fc3e70df609)

Como resolver?

**Comment by DiogoBispo012** [comment]
Olhe esse tutorial, talvez ajude: https://youtu.be/vUx1REIHL1o

**Comment by sergiobaiao** [comment]
tanto frontend estao rodando e comunicando um com o outro, com a exceção do erro no websocket mencionado acima. 
o config.json tambem foi criado

**Comment by rtenorioh** [comment]
Boa noite, se tiver utilizando a VPS gratuita nao ira rodar, pois a VPS gratuita é ARM e o Chrome roda com AMD
