### ISSUE TITLE
ERRO AO INSERIR API GPT

### ISSUE THREAD

**Issue by prdigennaro** [rtenorioh/Press-Ticket#109]
Olá quando tento inserir minha api do chat gpt o pressticket não deixa digitar retorna um erro "Integração não encontrada", assim não consigo nem digitar minha key

![WhatsApp Image 2023-05-25 at 11 28 18](https://github.com/rtenorioh/Press-Ticket/assets/14015778/5326ddd2-c0bb-4260-acd5-408efc1120b6)

**Comment by rtenorioh** [comment]
isso esta ocorrendo por vc nao ter rodado as seeds que inserem os valores default

**Comment by prdigennaro** [comment]
> isso esta ocorrendo por vc nao ter rodado as seeds que inserem os valores default

Uma dúvida, já não é a primeira vez que ocorre, quando sai uma versão nova eu utilizo o comando sh UPDATE para atualizar e as seed não rodam, agora qual seria o comando correto para resolver isso pode me ajudar?
ja ocorreu outras vezes e em outras atualização e acabei tendo que inserir por exemplo linha no banco de dados pq o update não fez automatico

**Comment by prdigennaro** [comment]
No UPDATE sempre ocorre isso 


EXECUTANDO O DB:MIGRATE


Sequelize CLI [Node: 16.20.0, CLI: 5.5.1, ORM: 5.22.5]

Loaded configuration file "dist/config/database.js".
No migrations were executed, database schema was already up to date.

EXECUTANDO O DB:SEED:ALL


Sequelize CLI [Node: 16.20.0, CLI: 5.5.1, ORM: 5.22.5]

Loaded configuration file "dist/config/database.js".
== 20200904070004-create-default-settings: migrating =======

ERROR: Validation error

**Comment by prdigennaro** [comment]
Alguem sabe como resolver?

**Comment by rtenorioh** [comment]
no backend cria o arquivo `sequelizeData.json`, nele cola o seguinte:

```
[
  "20200904070004-create-default-settings.js",
  "20200904070004-create-default-users.js",
  "20200904070006-create-apiToken-settings.js",
  "20230130004700-create-alltickets-settings.js",
  "20230326221400-create-ASC-settings.js",
  "20230326221600-create-created-settings.js"
]
```

e depois roda novamente o comando `npx sequelize db:seed:all`

**Comment by rtenorioh** [comment]
> > isso esta ocorrendo por vc nao ter rodado as seeds que inserem os valores default
> 
> Uma dúvida, já não é a primeira vez que ocorre, quando sai uma versão nova eu utilizo o comando sh UPDATE para atualizar e as seed não rodam, agora qual seria o comando correto para resolver isso pode me ajudar? ja ocorreu outras vezes e em outras atualização e acabei tendo que inserir por exemplo linha no banco de dados pq o update não fez automatico

Desde de 26 de março de 2023, subi a correção para evitar esse tipo de erro, passei as orientações no Grupo do Telegram, assim como passei o arquivo

**Comment by rtenorioh** [comment]
> > > > isso esta ocorrendo por vc nao ter rodado as seeds que inserem os valores default
> > > 
> > > 
> > > Uma dúvida, já não é a primeira vez que ocorre, quando sai uma versão nova eu utilizo o comando sh UPDATE para atualizar e as seed não rodam, agora qual seria o comando correto para resolver isso pode me ajudar? ja ocorreu outras vezes e em outras atualização e acabei tendo que inserir por exemplo linha no banco de dados pq o update não fez automatico
> > 
> > 
> > Desde de 26 de março de 2023, subi a correção para evitar esse tipo de erro, passei as orientações no Grupo do Telegram, assim como passei o arquivo
> 
> onde encontro o link para entrar no grupo do telegram?

No README.md tem o link do grupo no Telegram, mas segue o link: https://t.me/+akuzB2BzXitlMDkx
