### ISSUE TITLE
INTEGRAÇÃO COM O CHATGPT

### ISSUE THREAD

**Issue by Unifenas-bh** [rtenorioh/Press-Ticket#111]
Bom dia, tudo bem? como faço para utilizar o chatgpt pelo Press-ticket, eu coloquei a organization id e o apikey ... conseguir olhar o que eu precisava colocar /gpt   ou /gptM   mas a openai não me responde nem nada , teria algum procedimento que eu não me atentei e que você poderia me auxiliar.  cordialmente

**Comment by T3uZ** [comment]
Bom dia,
Você tem créditos para utilizar a API da Openai ?

**Comment by Unifenas-bh** [comment]
Bom dia , tudo bem ? eu fiz outra conta e testei utilizando  /gptM    para imagem ou /gpt  para texto   e não funcionou , instalei novamente  npm install openai  e também não funcionou.... teria outro procedimento que  preciso fazer para funcionar .
![image](https://github.com/rtenorioh/Press-Ticket/assets/113920249/6a2ed5c8-9660-4eb4-ba06-bb7ce7963fd9)

**Comment by rodrigofsantos** [comment]
estou com o mesmo problema !
