### ISSUE TITLE
Integração N8N

### ISSUE THREAD

**Issue by rodrigofsantos** [rtenorioh/Press-Ticket#112]
Senhores como faço para integrar o n8n com o pressticket ou seja digo para direcionar para o fluxo no n8n ? vou usar tudo localmente então ja setei a url na minha maquina e o n8n esta iniciado normalmente !!!

**Comment by smcfloripa** [comment]
Amigo se você estiver usando local é bem simples, basta você ir no n8n, e adicionar no seu fluxo um Webhook e na configuração dele você deve mudar de GET para POST copie o codigo de teste, no seu presticket você deve colar ele, na integração. retorne para o seu n8n e clique em teste do Webhook. e envie uma mensagem para o numero conectado, você ira receber um json com os dados do fluxo, lembrando que o sistema não ira enviar dados do presticket ele só envia os dados que o whatsapp esta enviando para o presticket, mas isso tem como você mudar mas terá que fazer uma personalização na rota.

**Comment by rodrigofsantos** [comment]
obrigado amigo ja havia dado certo !!!
