### ISSUE TITLE
Problema ao iniciar o front no  localhost

### ISSUE THREAD

**Issue by ojauumdev** [rtenorioh/Press-Ticket#114]
Boa tarde,
Pessoal estou com problemas ao rodar o npm start no frontend...
![image](https://github.com/rtenorioh/Press-Ticket/assets/115158157/3561ac37-228e-4b72-934f-ef433bed4f37)

**Comment by JoseMariani** [comment]
Debes corregir tu config.json para que trabaje con localhost, sigue la guia de instalacion par alocalhost que esta en este mismo repositorio, contactame si deseas mas ayuda.
