### ISSUE TITLE
Erro ao clica no canto superior direito Minha Conta / Profile

### ISSUE THREAD

**Issue by lucassaud** [rtenorioh/Press-Ticket#125]
Uncaught runtime errors:
×
ERROR
Objects are not valid as a React child (found: object with keys {name, version, systemVersion, private, dependencies, scripts, eslintConfig, browserslist}). If you meant to render a collection of children, use an array instead.
    in a (created by ForwardRef(Typography))
    in ForwardRef(Typography) (created by WithStyles(ForwardRef(Typography)))
    in WithStyles(ForwardRef(Typography)) (created by ForwardRef(Link))
    in ForwardRef(Link) (created by WithStyles(ForwardRef(Link)))
    in WithStyles(ForwardRef(Link)) (at layout/index.js:287)
    in span (at layout/index.js:286)
    in ul (created by ForwardRef(List))
    in ForwardRef(List) (created by WithStyles(ForwardRef(List)))
    in WithStyles(ForwardRef(List)) (created by ForwardRef(MenuList))
    in ForwardRef(MenuList) (created by ForwardRef(Menu))
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Transition)
    in Transition (created by ForwardRef(Grow))
    in ForwardRef(Grow) (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Modal))
    in div (created by ForwardRef(Modal))
    in ForwardRef(Portal) (created by ForwardRef(Modal))
    in ForwardRef(Modal) (created by ForwardRef(Popover))
    in ForwardRef(Popover) (created by WithStyles(ForwardRef(Popover)))
    in WithStyles(ForwardRef(Popover)) (created by ForwardRef(Menu))
    in ForwardRef(Menu) (created by WithStyles(ForwardRef(Menu)))
    in WithStyles(ForwardRef(Menu)) (at layout/index.js:264)
    in div (at layout/index.js:254)
    in div (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
    in WithStyles(ForwardRef(Toolbar)) (at layout/index.js:230)
    in header (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(AppBar))
    in ForwardRef(AppBar) (created by WithStyles(ForwardRef(AppBar)))
    in WithStyles(ForwardRef(AppBar)) (at layout/index.js:225)
    in div (at layout/index.js:196)
    in LoggedInLayout (at routes/index.js:34)
    in WhatsAppsProvider (at routes/index.js:33)
    in Switch (at routes/index.js:30)
    in AuthProvider (at routes/index.js:29)
    in Router (created by BrowserRouter)
    in BrowserRouter (at routes/index.js:28)
    in Routes (at App.js:123)
    in ThemeProvider (at App.js:122)
    in App (at src/index.js:9)
    in CssBaseline (created by WithStyles(CssBaseline))
    in WithStyles(CssBaseline) (at src/index.js:8)
Error: Objects are not valid as a React child (found: object with keys {name, version, systemVersion, private, dependencies, scripts, eslintConfig, browserslist}). If you meant to render a collection of children, use an array instead.
    in a (created by ForwardRef(Typography))
    in ForwardRef(Typography) (created by WithStyles(ForwardRef(Typography)))
    in WithStyles(ForwardRef(Typography)) (created by ForwardRef(Link))
    in ForwardRef(Link) (created by WithStyles(ForwardRef(Link)))
    in WithStyles(ForwardRef(Link)) (at layout/index.js:287)
    in span (at layout/index.js:286)
    in ul (created by ForwardRef(List))
    in ForwardRef(List) (created by WithStyles(ForwardRef(List)))
    in WithStyles(ForwardRef(List)) (created by ForwardRef(MenuList))
    in ForwardRef(MenuList) (created by ForwardRef(Menu))
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Transition)
    in Transition (created by ForwardRef(Grow))
    in ForwardRef(Grow) (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Modal))
    in div (created by ForwardRef(Modal))
    in ForwardRef(Portal) (created by ForwardRef(Modal))
    in ForwardRef(Modal) (created by ForwardRef(Popover))
    in ForwardRef(Popover) (created by WithStyles(ForwardRef(Popover)))
    in WithStyles(ForwardRef(Popover)) (created by ForwardRef(Menu))
    in ForwardRef(Menu) (created by WithStyles(ForwardRef(Menu)))
    in WithStyles(ForwardRef(Menu)) (at layout/index.js:264)
    in div (at layout/index.js:254)
    in div (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
    in WithStyles(ForwardRef(Toolbar)) (at layout/index.js:230)
    in header (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(AppBar))
    in ForwardRef(AppBar) (created by WithStyles(ForwardRef(AppBar)))
    in WithStyles(ForwardRef(AppBar)) (at layout/index.js:225)
    in div (at layout/index.js:196)
    in LoggedInLayout (at routes/index.js:34)
    in WhatsAppsProvider (at routes/index.js:33)
    in Switch (at routes/index.js:30)
    in AuthProvider (at routes/index.js:29)
    in Router (created by BrowserRouter)
    in BrowserRouter (at routes/index.js:28)
    in Routes (at App.js:123)
    in ThemeProvider (at App.js:122)
    in App (at src/index.js:9)
    in CssBaseline (created by WithStyles(CssBaseline))
    in WithStyles(CssBaseline) (at src/index.js:8)
    at throwOnInvalidObjectType (http://localhost:3333/static/js/bundle.js:145667:19)
    at createChild (http://localhost:3333/static/js/bundle.js:145867:11)
    at reconcileChildrenArray (http://localhost:3333/static/js/bundle.js:146071:29)
    at reconcileChildFibers (http://localhost:3333/static/js/bundle.js:146403:18)
    at reconcileChildren (http://localhost:3333/static/js/bundle.js:148545:32)
    at updateHostComponent (http://localhost:3333/static/js/bundle.js:149003:7)
    at beginWork (http://localhost:3333/static/js/bundle.js:150117:18)
    at HTMLUnknownElement.callCallback (http://localhost:3333/static/js/bundle.js:134130:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3333/static/js/bundle.js:134174:20)
    at invokeGuardedCallback (http://localhost:3333/static/js/bundle.js:134222:35)
ERROR
Objects are not valid as a React child (found: object with keys {name, version, systemVersion, private, dependencies, scripts, eslintConfig, browserslist}). If you meant to render a collection of children, use an array instead.
    in a (created by ForwardRef(Typography))
    in ForwardRef(Typography) (created by WithStyles(ForwardRef(Typography)))
    in WithStyles(ForwardRef(Typography)) (created by ForwardRef(Link))
    in ForwardRef(Link) (created by WithStyles(ForwardRef(Link)))
    in WithStyles(ForwardRef(Link)) (at layout/index.js:287)
    in span (at layout/index.js:286)
    in ul (created by ForwardRef(List))
    in ForwardRef(List) (created by WithStyles(ForwardRef(List)))
    in WithStyles(ForwardRef(List)) (created by ForwardRef(MenuList))
    in ForwardRef(MenuList) (created by ForwardRef(Menu))
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Transition)
    in Transition (created by ForwardRef(Grow))
    in ForwardRef(Grow) (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Modal))
    in div (created by ForwardRef(Modal))
    in ForwardRef(Portal) (created by ForwardRef(Modal))
    in ForwardRef(Modal) (created by ForwardRef(Popover))
    in ForwardRef(Popover) (created by WithStyles(ForwardRef(Popover)))
    in WithStyles(ForwardRef(Popover)) (created by ForwardRef(Menu))
    in ForwardRef(Menu) (created by WithStyles(ForwardRef(Menu)))
    in WithStyles(ForwardRef(Menu)) (at layout/index.js:264)
    in div (at layout/index.js:254)
    in div (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
    in WithStyles(ForwardRef(Toolbar)) (at layout/index.js:230)
    in header (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(AppBar))
    in ForwardRef(AppBar) (created by WithStyles(ForwardRef(AppBar)))
    in WithStyles(ForwardRef(AppBar)) (at layout/index.js:225)
    in div (at layout/index.js:196)
    in LoggedInLayout (at routes/index.js:34)
    in WhatsAppsProvider (at routes/index.js:33)
    in Switch (at routes/index.js:30)
    in AuthProvider (at routes/index.js:29)
    in Router (created by BrowserRouter)
    in BrowserRouter (at routes/index.js:28)
    in Routes (at App.js:123)
    in ThemeProvider (at App.js:122)
    in App (at src/index.js:9)
    in CssBaseline (created by WithStyles(CssBaseline))
    in WithStyles(CssBaseline) (at src/index.js:8)
Error: Objects are not valid as a React child (found: object with keys {name, version, systemVersion, private, dependencies, scripts, eslintConfig, browserslist}). If you meant to render a collection of children, use an array instead.
    in a (created by ForwardRef(Typography))
    in ForwardRef(Typography) (created by WithStyles(ForwardRef(Typography)))
    in WithStyles(ForwardRef(Typography)) (created by ForwardRef(Link))
    in ForwardRef(Link) (created by WithStyles(ForwardRef(Link)))
    in WithStyles(ForwardRef(Link)) (at layout/index.js:287)
    in span (at layout/index.js:286)
    in ul (created by ForwardRef(List))
    in ForwardRef(List) (created by WithStyles(ForwardRef(List)))
    in WithStyles(ForwardRef(List)) (created by ForwardRef(MenuList))
    in ForwardRef(MenuList) (created by ForwardRef(Menu))
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Transition)
    in Transition (created by ForwardRef(Grow))
    in ForwardRef(Grow) (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Modal))
    in div (created by ForwardRef(Modal))
    in ForwardRef(Portal) (created by ForwardRef(Modal))
    in ForwardRef(Modal) (created by ForwardRef(Popover))
    in ForwardRef(Popover) (created by WithStyles(ForwardRef(Popover)))
    in WithStyles(ForwardRef(Popover)) (created by ForwardRef(Menu))
    in ForwardRef(Menu) (created by WithStyles(ForwardRef(Menu)))
    in WithStyles(ForwardRef(Menu)) (at layout/index.js:264)
    in div (at layout/index.js:254)
    in div (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
    in WithStyles(ForwardRef(Toolbar)) (at layout/index.js:230)
    in header (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(AppBar))
    in ForwardRef(AppBar) (created by WithStyles(ForwardRef(AppBar)))
    in WithStyles(ForwardRef(AppBar)) (at layout/index.js:225)
    in div (at layout/index.js:196)
    in LoggedInLayout (at routes/index.js:34)
    in WhatsAppsProvider (at routes/index.js:33)
    in Switch (at routes/index.js:30)
    in AuthProvider (at routes/index.js:29)
    in Router (created by BrowserRouter)
    in BrowserRouter (at routes/index.js:28)
    in Routes (at App.js:123)
    in ThemeProvider (at App.js:122)
    in App (at src/index.js:9)
    in CssBaseline (created by WithStyles(CssBaseline))
    in WithStyles(CssBaseline) (at src/index.js:8)
    at throwOnInvalidObjectType (http://localhost:3333/static/js/bundle.js:145667:19)
    at createChild (http://localhost:3333/static/js/bundle.js:145867:11)
    at reconcileChildrenArray (http://localhost:3333/static/js/bundle.js:146071:29)
    at reconcileChildFibers (http://localhost:3333/static/js/bundle.js:146403:18)
    at reconcileChildren (http://localhost:3333/static/js/bundle.js:148545:32)
    at updateHostComponent (http://localhost:3333/static/js/bundle.js:149003:7)
    at beginWork (http://localhost:3333/static/js/bundle.js:150117:18)
    at HTMLUnknownElement.callCallback (http://localhost:3333/static/js/bundle.js:134130:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3333/static/js/bundle.js:134174:20)
    at invokeGuardedCallback (http://localhost:3333/static/js/bundle.js:134222:35)

**Comment by lucassaud** [comment]
Hi. I dont have money. I try to put the code to run and ask chatgpt for help. Tkd.

**Comment by mdestafadilah** [comment]
> Hi. I dont have money. I try to put the code to run and ask chatgpt for help. Tkd.

did chatgpt solved this problem?

**Comment by lucassaud** [comment]
> > Hi. I dont have money. I try to put the code to run and ask chatgpt for help. Tkd.
> 
> did chatgpt solved this problem?

hi, yeah. i have found another solution.

**Comment by mdestafadilah** [comment]
> > > Hi. I dont have money. I try to put the code to run and ask chatgpt for help. Tkd.
> > 
> > 
> > did chatgpt solved this problem?
> 
> hi, yeah. i have found another solution.

hi, can you share detail, and how to resolve this?

**Comment by lucassaud** [comment]
> > > > Hi. I dont have money. I try to put the code to run and ask chatgpt for help. Tkd.
> > > 
> > > 
> > > did chatgpt solved this problem?
> > 
> > 
> > hi, yeah. i have found another solution.
> 
> hi, can you share detail, and how to resolve this?

AutoAtende SaaS
With Kanban and Night Mode
Working with Baileys 6.5.0
Updated references to the @WhiskeySockets/Baileys library
Modified AnyWASocket, WALegacySocket, LegacyAuthenticationCreds
Fixed Bot repeats Menu

Fontend Updates:
Added Dark Theme
Added Kanban Module

Added Insta and Facebook connections - Under Review (Library out of date 9/13, target 16)
Added Task List (Function that uses browser cache)

Chatbot Type = Text Only
Removed deprecated options, Lists and Buttons.

It is not necessary to have an active cell phone and connected to the internet to receive messages.
Quick Replies > OK
Media Upload > OK
Message scheduling > OK
Import contacts from phone > OK
Export contact list .csv > OK
Sending campaigns > OK
Download and Import Contact List in Campaigns > OK
Create campaign contacts directly from the panel > OK
CallBack GestãoNet via Insomnia > OK


These are the changes I made to the system. But I'm selling them. Value: USD 150

**Comment by mdestafadilah** [comment]
> > > > > Hi. I dont have money. I try to put the code to run and ask chatgpt for help. Tkd.
> > > > 
> > > > 
> > > > did chatgpt solved this problem?
> > > 
> > > 
> > > hi, yeah. i have found another solution.
> > 
> > 
> > hi, can you share detail, and how to resolve this?
> 
> AutoAtende SaaS With Kanban and Night Mode Working with Baileys 6.5.0 Updated references to the @WhiskeySockets/Baileys library Modified AnyWASocket, WALegacySocket, LegacyAuthenticationCreds Fixed Bot repeats Menu
> 
> Fontend Updates: Added Dark Theme Added Kanban Module
> 
> Added Insta and Facebook connections - Under Review (Library out of date 9/13, target 16) Added Task List (Function that uses browser cache)
> 
> Chatbot Type = Text Only Removed deprecated options, Lists and Buttons.
> 
> It is not necessary to have an active cell phone and connected to the internet to receive messages. Quick Replies > OK Media Upload > OK Message scheduling > OK Import contacts from phone > OK Export contact list .csv > OK Sending campaigns > OK Download and Import Contact List in Campaigns > OK Create campaign contacts directly from the panel > OK CallBack GestãoNet via Insomnia > OK
> 
> These are the changes I made to the system. But I'm selling them. Value: USD 150

aha, thanks for the pointing.
