### ISSUE TITLE
Whatsapp contecta mas pressticket não

### ISSUE THREAD

**Issue by ivam** [rtenorioh/Press-Ticket#131]
Após ler o QR code o whatsapp informa estar conectado, mas o whaticket não mostra estar conectado

Alguem pode me ajudar? estou com varios clientes nessa situação, mesmo instalando do zero acontece isso!

**Comment by JoseMariani** [comment]
Lo he resuelto pero no funciona el envio de audios, abria que revisar esa parte en el codigo. Si necesitas que lo resuelva contactame y coordinamos.

**Comment by rumeniquej** [comment]
Veja se te ajuda essa solução

https://github.com/canove/whaticket-community/issues/629
