### ISSUE TITLE
Multi Empresa

### ISSUE THREAD

**Issue by HideBad** [rtenorioh/Press-Ticket#142]
Seria interessante, que o sistema fosse multi empresas, empresas distintas com conexões e gestão de usuários no mesmo acesso.

**Comment by rtenorioh** [comment]
Bom dia, o Press Ticket é um sistema Single, ele não é SAAS, até mesmo para converter para SAAS o ideal seria tbm trocar a lib atual (wwejs), quem sabe assim que finalizar a integração Multicanais não venha a virar SAAS, tendo em vista que as libs são externas
