### ISSUE TITLE
Cannot find file './config.json' in '.\src'.

### ISSUE THREAD

**Issue by GGDiniz** [rtenorioh/Press-Ticket#143]
![error](https://github.com/user-attachments/assets/38d27a5c-477b-40e4-922e-2deca2c657a6)

**Comment by rtenorioh** [comment]
Boa noite, pegou esse erro por ter pulado parte dos comandos de instalação, pois faltou gerar esse arquivo, porem fique tranquilo que já esta em testes a v1.10.0 que não terá mais esse arquivo e vc poderá configurar as cores e logos dentro do sistema por meio de um formulario

**Comment by rtenorioh** [comment]
Problema resolvido na PR https://github.com/rtenorioh/Press-Ticket/pull/144
