### ISSUE TITLE
Error 502 backend

### ISSUE THREAD

**Issue by tonnybarros** [rtenorioh/Press-Ticket#2]
Normal
https://zap.tectonny.com.br/

Error backend
https://adminzap.tectonny.com.br/

I followed step by step the script to install.
Using ubuntu 18

**Comment by rtenorioh** [comment]
Verifica se fez os apontamentos corretos no env e se na hora de apontar o Nginx fez correto

**Comment by tonnybarros** [comment]
Verifiquei 3 vezes, tudo conforme a instalação.
Esse servidor é de teste, que olhar com os dados root?

Em dom., 1 de mai. de 2022 16:29, Robson Tenorio ***@***.***>
escreveu:

**Comment by rtenorioh** [comment]
Porque o erro está no arquivo do Nginx, pode ser que vc possa ter add um espaço a mais ou até mesmo invertido as URL ou não ter alterado a porta, pois fiz duas instalações recentes e estão rodando de Boa.

**Comment by tonnybarros** [comment]
Coloquei exatamente como esta no tutorial, sera que esta invertido?

**Comment by rtenorioh** [comment]
Por favor, para poder lhe ajudar, se tiver rodando o backend com o pm2, de um pm2 stop no ID do seu back e depois de um npm start no backend, assim terá o erro no terminal, mande o print desse erro que poderei te ajudar melhor.

**Comment by tonnybarros** [comment]
Zerei o servidor, e vou tentar novamente

Em dom., 1 de mai. de 2022 às 20:38, Robson Tenorio <
***@***.***> escreveu:

**Comment by rtenorioh** [comment]
entendi, qualquer coisa me chame novamente

**Comment by tonnybarros** [comment]
Mesma coisa, novo servidor e nada.
Olha o print final da instalação.
https://atendimento.tectonny.com.br/

https://adminchat.tectonny.com.br/ erro

Consegue fazer para mim
Novo servidor
IPv4 49.12.185.108
IPv6 2a01:4f8:c17:3d08::/64
User root
Password 4mJt7rfwgMgewK3wgNK4
[image: image.png]

Em dom., 1 de mai. de 2022 às 21:28, Robson Tenorio <
***@***.***> escreveu:

**Comment by tonnybarros** [comment]
Novo servidor
IP: 49.12.185.108
Senha: 988690Bren

Veja nas instruções la no github se não está algo invertido.

Em dom., 1 de mai. de 2022 às 21:57, Tonny Barros ***@***.***>
escreveu:

**Comment by rtenorioh** [comment]
então, como disse fiz duas instalações recentes e estão ok.
preciso que mande o print do terminal ao rodar o comando npm start no backend, pois nele irá mostrar onde seu backend esta quebrando

**Comment by rtenorioh** [comment]
Outra dúvida, qual VPS esta usando?

**Comment by tonnybarros** [comment]
Uso servidores da Hetzer, mais de 5 anos lá.
É o servidor? Vi que o erro 502 foi resolvido, só não consegui logar

Em dom., 1 de mai. de 2022 às 23:06, Robson Tenorio <
***@***.***> escreveu:

**Comment by rtenorioh** [comment]
fiz a instalação normal como no [INSTALL.md](https://github.com/rtenorioh/Press-Ticket/blob/main/INSTALL.md), porém não esta permitindo login devido eu ter trocado a url no env do front, mas já corrigi e esta funcionando normalmente.

![image](https://user-images.githubusercontent.com/49109977/166177859-20669fff-63aa-4b0d-9aac-d191b5c76e23.png)

**Comment by tonnybarros** [comment]
Para eu usar 2 whatsapp eu já entendi que tenho que colocar o limite de
conexão em 2, eu fiz isso, o que preciso fazer para surtir efeito?
Reiniciar o serviço? sem sim, como faço?

Em dom., 1 de mai. de 2022 às 23:44, Tonny Barros ***@***.***>
escreveu:

**Comment by rtenorioh** [comment]
No env do backend você irá procurar por:

USER_LIMIT=3 (Limite de usuários)
CONNECTIONS_LIMIT=1 (Limite de Conexões)

e vai alterar de acordo com a sua necessidade.

após realizar as alterações, deverá dar os seguintes comandos:

`pm2 stop 0`
`npm run build`
`pm2 start 0`

Lembrando que deverá estar logado na VPS como deploy, onde a senha ta como tonny

**Comment by tonnybarros** [comment]
Fiz isso e o comando npm run build deu esse erro
[image: image.png]

Em dom., 1 de mai. de 2022 às 23:59, Robson Tenorio <
***@***.***> escreveu:

**Comment by rtenorioh** [comment]
Vc está colando a imagem de forma incorreta, pois não abre nada, e o erro que deve estar tendo é por tentar alterar como root e vc deve fazer as alterações como deploy, usando o comando:
`su deploy`
`su - ${USER}`
`tonny`

Apenas após isso que pode fazer as alterações

**Comment by tonnybarros** [comment]
Beleza, agradeço, vou deixar meu zap 21-979123851
Se precisar de algo relacionado a conserto de tv e som, e só me chamar,
esse é o meu ramo de trabalho.

Em seg., 2 de mai. de 2022 às 00:15, Robson Tenorio <
***@***.***> escreveu:

**Comment by tonnybarros** [comment]
Poxa, show de bola,saberia dizer onde eu errei para gerar erro 502 no
backend?
E eu posso usar sem problemas, o projeto está funcionando bem?

Em dom., 1 de mai. de 2022 às 23:35, Robson Tenorio <
***@***.***> escreveu:

**Comment by tonnybarros** [comment]
Apesar do erro, funcionou, obrigadooooo, vou acompanhar todas as
atualizações


Em seg., 2 de mai. de 2022 às 00:10, Tonny Barros ***@***.***>
escreveu:

**Comment by tonnybarros** [comment]
Tem como olhar?
5.161.105.157

Root
988690Bren

Já zerei o servidor 3 vezes, e sempre no mesmo erro, a instalação está
correta no site?

Em dom., 1 de mai. de 2022 16:42, Robson Tenorio ***@***.***>
escreveu:
