### ISSUE TITLE
Tickets Duplicados

### ISSUE THREAD

**Issue by italow6** [rtenorioh/Press-Ticket#20]
![173395309-bee271e8-bf25-40ec-b641-43ca76f6480f](https://user-images.githubusercontent.com/6899447/173578887-42f167cc-83f4-4502-9dbb-7cc4bf438ea5.jpg)
![173395157-f68be604-1263-4288-a2f3-f7ae36ef4525](https://user-images.githubusercontent.com/6899447/173578904-5293083c-1315-4182-bcf9-322a696d512f.png)

Algumas conversas estão ficando duplicadas, o que posso fazer para solucionar?

**Comment by tonnybarros** [comment]
Qual versão está usando?
Não vi esse big ainda em nenhum teste, não teria duas conexões ativas?

**Comment by rtenorioh** [comment]
> ![173395309-bee271e8-bf25-40ec-b641-43ca76f6480f](https://user-images.githubusercontent.com/6899447/173578887-42f167cc-83f4-4502-9dbb-7cc4bf438ea5.jpg) ![173395157-f68be604-1263-4288-a2f3-f7ae36ef4525](https://user-images.githubusercontent.com/6899447/173578904-5293083c-1315-4182-bcf9-322a696d512f.png)
> 
> Algumas conversas estão ficando duplicadas, o que posso fazer para solucionar?

Qual versão esta usando, pois não é o Press Ticket...
Outro detalhe, o problema ainda persiste? pois isso pode ser um erro do próprio whatsapp de demorar a fazer a entrega da mensagem, assim gerando uma duplicata...
