### ISSUE TITLE
Problem after upgrading from 1.0.4 to 1.0.6

### ISSUE THREAD

**Issue by philipzan** [rtenorioh/Press-Ticket#23]
Hi,

After updating from version 1.0.4 to version 1.0.6, it appears that the migration of the database needs fixing.

```bash

git pull
cd backend
npm install
rm -rf dist
npm run build
```
```
npx sequelize db:migrate
npx sequelize db:seed
```
``Loaded configuration file "dist/config/database.js".``
``No migrations were executed, database schema was already up to date.``

The hours are displayed in the interface but are not saved with an error that the table does not exist.
The settings page also displays a white page

**Comment by rtenorioh** [comment]
Thanks for the information, we really identified this problem and intend to fix it in the next update.
