### ISSUE TITLE
Mensagem fora do horário de atendimento.

### ISSUE THREAD

**Issue by tonnybarros** [rtenorioh/Press-Ticket#3]
Olá, é possível configurar horário de atendimento?
Quando receber mensagem fora do horário em vez de vir o menu, vir uma mensagem informando os horários de atendimento.

Ou se for muito complicado, desabilitar o menu normal dos setores, fora do horário de atendimento, assim o wb informa no app normal

**Comment by rtenorioh** [comment]
Bom dia, na proxima atualização será implementado o horário de atendimento por conexão, ia soltar essa semana, porém devido a muitas atividades da faculdade e provas acabei não tendo tempo de fazer os ultimos ajustes, mas já esta quase pronto..

**Comment by tonnybarros** [comment]
Show Robson, vou ficar aguardando.
Vai ser possível atualizar a já instalada?

**Comment by rtenorioh** [comment]
estou fazendo os testes de implementação agora, nisso estou ajustando o frontend para poder inserir nas conexões e setores os horários e mensagens de ausência, se tudo de certo hoje mesmo já estará disponivel

**Comment by tonnybarros** [comment]
Opaaa, showww, vou ficar no F5 hahahah

**Comment by rtenorioh** [comment]
calma que vai demorar um pouco, pois daqui a pouco levo meu filho na escola kkkkkkk

**Comment by tonnybarros** [comment]
Nada ainda?

Se precisar posso ser o beta teste kkkkk
Tenho um cloud só para testes

**Comment by tonnybarros** [comment]
Robson, fim de semana chegou, bora mexer no projeto ahahahh, sobe ele para eu testar

**Comment by rtenorioh** [comment]
https://github.com/rtenorioh/Press-Ticket/commit/0a86350a3a6f7d9422c3826ca0eea7d807f864ba

Horário de atendimento por setor.
