### ISSUE TITLE
Problema ao visualizar ticket

### ISSUE THREAD

**Issue by emersonart** [rtenorioh/Press-Ticket#37]
![image](https://user-images.githubusercontent.com/5253941/181833905-8f7408e5-9c72-447e-ba90-a07eeea2d47a.png)

* Com a nova versão não abre o ticket ao clicar no ticket (o mesmo serve ao tentar abrir pela notificação no canto superior).
* Os botões em cada ticket estão errados, mesmo com ticket aberto aparece o botão de reabrir, mas mesmo clicando nele na verdade remove da fila e joga para aguardando (neste caso a conversa abre mesmo no status aguardando)
* Acessando a url do ticket a conversa aparece.

tudo isso não gera nenhum erro no console, exceto quando clica em reabrir (mesmo com o ticket aberto) para burlar o bug estou utilizando assim, reabro (que na verdade joga pra aguardando e depois aceito novamente) e aí ao clicar em reabrir, surge o erro no log:

![image](https://user-images.githubusercontent.com/5253941/181835226-d268e453-c053-46d4-abdd-d258367663d6.png)

A versão utilizada não faço nenhuma alteração, utilizo a versão pura do pressticket. 

Verifiquei também que a versão demo apresenta o mesmo problema descrito.

**Comment by rtenorioh** [comment]
[Correção para aceitar ticket](https://github.com/rtenorioh/Press-Ticket/commit/d61d67da2e64b400c47091346ed29edff7c3919b)
