### ISSUE TITLE
Como corrigir erro ao RESPONDER a GRUPOS.

### ISSUE THREAD

**Issue by isoazevedo** [rtenorioh/Press-Ticket#39]
Corrigido com a versão whatsap-web.js 1.17.1 da seguinte forma.

Arquivo:
backend/src/helpers/SerializeWbotMsgId.ts

Adicionada a estrutura da constante SerializeWbotMsgId os seguintes valores.

```
const SerializeWbotMsgId = (ticket: Ticket, message: Message): string => {

  let SeGrupo = 'g.us_' + message.id + '_'+ message.contact.number + '@c.us';
  let SeIndiv = 'c.us_' + message.id;

  const serializedMsgId = `${message.fromMe}_${ticket.contact.number}@${
    ticket.isGroup ? SeGrupo : SeIndiv }`;

  return serializedMsgId;
};
```

**Comment by rtenorioh** [comment]
Boa tarde, esse erro que cita seria ocasionado como?

voltando hoje, meu PC tinha dado ruim

**Comment by rtenorioh** [comment]
Feita a correção usando a sua solução: https://github.com/rtenorioh/Press-Ticket/commit/9721da147cd7916c1b2577f20bdd549a1bd91edc

Obrigado pela contribuição.
