### ISSUE TITLE
Notificar usuário somente tickets que sejam de seus setores

### ISSUE THREAD

**Issue by pedriin647** [rtenorioh/Press-Ticket#45]
Hoje no pressticket, caso alguém mande uma mensagem antes mesmo de escolher uma fila(setor) para ser atendido todos os usuários são notificados. Teria como resolver isso?

**Comment by rtenorioh** [comment]
Bom dia @pedriin647 

estou finalizando umas implementações da v1.2.0 e já estou trabalhando nas filas cinzas tbm

**Comment by pedriin647** [comment]
Bom dia! Ótimo então, estou no aguardo!

**Comment by pedriin647** [comment]
Bom dia, vi que a release 1.2.0 já saiu.. já está funcionando com esta funcionalidade?
