### ISSUE TITLE
Mensagem deletar ticket está com erro segue código de correção

### ISSUE THREAD

**Issue by wslsolucoes** [rtenorioh/Press-Ticket#46]
confirmationModal: {
          title: "Deletar o ticket ",
          titleFrom: "do contato ",
          message: "Atenção! Todas as mensagens relacionadas ao ticket serão perdidas.",
        },

**Comment by rtenorioh** [comment]
Corrigido no commit: https://github.com/rtenorioh/Press-Ticket/commit/7e8436fa11740d1f6271b3d321165ca763eb69c6
