### ISSUE TITLE
Mensagem transferir campo setor com erro segue código 

### ISSUE THREAD

**Issue by wslsolucoes** [rtenorioh/Press-Ticket#47]
Abrir 

src/translate/languages/pt.js

Linha 263 substituir por 
        fieldQueuePlaceholder: "Transferir para o Setor",
        fieldQueueLabel: "Transferir para o Setor",

**Comment by rtenorioh** [comment]
Corrigido no commit: https://github.com/rtenorioh/Press-Ticket/commit/1291369d633a7ca1f0d0a5bb914371f1e2039655
