### ISSUE TITLE
Opção de visulizar a conversa antes de aceitar.

### ISSUE THREAD

**Issue by tonnybarros** [rtenorioh/Press-Ticket#5]
Eu já peguei uma modificação e estou usando no Press-Ticket, seria interessante adicionar essa função, funcionando bem até agora.
Criei um fork e coloquei a modificação, caso queira ver.

**Comment by rtenorioh** [comment]
Show, irei verificar logo mais, porém no caso como vc ja testou e caso queira fazer um PR fique a vontade, toda contibuição é bem vinda.

**Comment by tonnybarros** [comment]
Fechado, vou fazer

**Comment by rtenorioh** [comment]
https://github.com/rtenorioh/Press-Ticket/pull/6

Acabei de fazer o merge da PR#6, no entanto exclui referente a rotação de imagem, para que não misture conteúdos diferentes, pode criar um novo PR para ele

**Comment by tonnybarros** [comment]
Ok, entendi, mas o arquivo 
frontend/src/components/ModalImageCors/index.js

Sumiu? Do seu projeto, e do meu.
Nem a pasta ModalImageCors eu estou achando.

**Comment by rtenorioh** [comment]
Sim, vou subir novamente na atualização que vou fazer agora.
