### ISSUE TITLE
Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by pedriin647** [rtenorioh/Press-Ticket#53]
ao receber um ticket no setor, o press ticket buga, tendo que atualizar a página pra funcionar. e no console exibe o seguinte erro.

![image](https://user-images.githubusercontent.com/86935973/196485746-f9be4d11-b23c-479d-86b9-181ba231caea.png)

Estava tentando fazer um tipo de verificação, como:

if(ticket !== undefined){

}

dentro do ticketList, mas não tive sucesso...

**Comment by pedriin647** [comment]
obs: estou no localhost. já dei rebuild tanto no front quanto backend

**Comment by rtenorioh** [comment]
Boa noite, vc tem que verificar quais modificações fez, pois acabei de subir a v1.3.0 e nao peguei esse erro em localhost, nem na versão que esta na VPS, outro detalhe, em localhost não é feito o build do frontend.

**Comment by pedriin647** [comment]
estava na 1.2.1, vou atualizar aqui pra ver
