### ISSUE TITLE
mistake made within the english translation

### ISSUE THREAD

**Issue by egorky** [rtenorioh/Press-Ticket#55]
please, change in the file frontend/src/translate/languages/en.js the second line from 
`  EN: {`

to 

`  en: {`

otherwise, English translation won't work.

**Comment by rtenorioh** [comment]
Correção realizada no commit: https://github.com/rtenorioh/Press-Ticket/commit/7fc2d00aec6485e4222ee9115fa1f4ec129e357f

**Comment by egorky** [comment]
Sorry to re open this issue, but the same mistake was made in two other places /frontend/src/translate/languages/en.js and /frontend/src/translate/languages/es.js. One must change "Login" to "login" in order for the translations work.
<img width="362" alt="image" src="https://user-images.githubusercontent.com/54412925/198484546-f8ed1db3-922e-4080-bef0-8a14b9f2af01.png">
