### ISSUE TITLE
Sistema pesado

### ISSUE THREAD

**Issue by Gedehamsen021** [rtenorioh/Press-Ticket#59]
ola eu estou com problema de desempenho tanto no servidor quanto nos terminais, teria alguma maneira de fazer com que os tickets fizesse load apenas do ticket atual? pois ele está pegando todos os tickets e como são varios por dia acaba travando a pagina quando recebe uma mensagem e aumenta para 2gb o uso de memoria

**Comment by Anderson-Nascimento-Mendonca** [comment]
Acho que isso resolveria se não puxasse todo o historio para cada ticket, cada ticket ficasse so naquele ticket, pois quando você aceitar um ticket trás todo historia da conversa para pagina.
