### ISSUE TITLE
Dias para horário de funcionamento

### ISSUE THREAD

**Issue by ricardomecca** [rtenorioh/Press-Ticket#61]
Olá,

Gostei das inovações nesta versão, principalmente a de horário de funcionamento. Mas gostaria de propor se há possibilidade de adicionar dias para funcionamento dos setores, exemplo: Segunda a Sábado. E assim selecionar o horário. Acredito que seria uma função fundamental e que ajudaria muito a propagar essa versão

**Comment by pedriin647** [comment]
interessante, vou ver se consigo implementar isso daqui
