### ISSUE TITLE
error TS2688: Cannot find type definition file for 'pino-pretty'.

### ISSUE THREAD

**Issue by Manfrinne** [rtenorioh/Press-Ticket#62]
I'm having problems when I run the command 'npm run build', does anyone know what this is?

![image](https://user-images.githubusercontent.com/58799400/201165403-65989a43-e676-45ab-b3d7-2eff0186b8c5.png)

The versions of npm, node and tsc are:

![image](https://user-images.githubusercontent.com/58799400/201165860-5cad41be-5ef5-4e76-9a82-9a013b9ec4aa.png)

**Comment by fitwan2014** [comment]
run npm install -D pino-pretty 
then 
npm run build

**Comment by wlfonseca** [comment]
npm r pino-pretty
npm i pino-pretty
npm run build
