### ISSUE TITLE
Erro após realizar o update

### ISSUE THREAD

**Issue by leonardocassio** [rtenorioh/Press-Ticket#65]
Boa tarde, 

Galera após realizar o Update do sistema para a ultima versão obtive o erro mencionado abaixo: 

Error: ENOENT: no such file or directory, stat '/home/deploy/Press-Ticket/frontend/build/index.html'

SO: Ubuntu 20.04.5 LTS

![image](https://user-images.githubusercontent.com/9685537/204891328-294402e7-4d2b-4299-b814-08a0d9fcb747.png)

**Comment by leonardocassio** [comment]
Resolvido realizando o Update manual!

cd ~
cd  Press-Ticket
git pull
cd backend
npm install
rm -rf dist
npm run build
npx sequelize db:migrate
npx sequelize db:seed
cd ../frontend
npm install
rm -rf build
npm run build
pm2 restart all

**Comment by diogotoriani** [comment]
Eu fiz uma instalação nova esta semana, teve o mesmo erro... o instalador automático não está criando o arquivo config.json no frontend
