### ISSUE TITLE
Front ficando com a interface congelada

### ISSUE THREAD

**Issue by lbodev** [rtenorioh/Press-Ticket#68]
Olá, estou utilizando o pressticket e me deparei com o problema de congelamento da interface no frontend.
Do nada a interface fica congelada sendo necessário atualizar a página novamente (F5).

**Comment by maercioliveira** [comment]
Veja no console se há erro de sockets.

**Comment by abnersiqueira** [comment]
> 

Peguei esse erro de sockets tem solução?

**Comment by alternativa2216** [comment]
to preso no mesmo erro de sockets

**Comment by codsec** [comment]
@alternativa2216 @abnersiqueira @maercioliveira @lbodev alguem conseguiu achar uma possivel solução? estou sofrendo desse freeze a cada 5minutos praticamente...

**Comment by alternativa2216** [comment]
também tenho o mesmo problema, como eu utilizei um instalador automático eu tenho que atualizar por ele ai roda de novo, mais para toda hora

**Comment by abnersiqueira** [comment]
@codsec sem solução ainda amigo..
tanto local como via docker

**Comment by codsec** [comment]
> @codsec sem solução ainda amigo.. tanto local como via docker


> também tenho o mesmo problema, como eu utilizei um instalador automático eu tenho que atualizar por ele ai roda de novo, mais para toda hora

Eu encontrei uma solução, check o console(f12) do seu navegador e vejam se quando a pagina web trava aparece a messagem, "Blocked by CORS" caso seja isso, a solução acaba sendo "SIMPLES" basta instalar um SSL no servidor de vocês, eu recomendo utilizar uma VPS e apontar um dominio já com SSL utilizando o CloudFlare para facilitar
