### ISSUE TITLE
.wwwjs "LegacyPhoneFeatures"

### ISSUE THREAD

**Issue by abnersiqueira** [rtenorioh/Press-Ticket#69]
0|backend  | Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'LegacyPhoneFeatures')
0|backend  |     at __puppeteer_evaluation_script__:13:76
0|backend  |     at ExecutionContext._evaluateInternal (/app/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
0|backend  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|backend  |     at async ExecutionContext.evaluate (/app/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
0|backend  |     at async Client.initialize (/app/backend/node_modules/whatsapp-web.js/src/Client.js:267:9)

**Comment by rtenorioh** [comment]
Corrigido com a atualização da lib wwebjs de 1.18.4 para 1.19.2 https://github.com/rtenorioh/Press-Ticket/commit/8fbdd3ce8873fe6113c25f76ed8fa4465b17df67
