### ISSUE TITLE
nao abrir ticket ao enviar mensagens via API

### ISSUE THREAD

**Issue by heenriquega** [rtenorioh/Press-Ticket#7]
Olá estou acompanhando seu projeto, atualmente uso o Whaticket do canove, no forum fizemos algumas modificações para que quando envie mensagem por api nao abra um ticket, testei no seu projeto nao funcionou.

em /backend/src/controllers/ApiController.ts

fazemos o import

`import UpdateTicketService from "../services/TicketServices/UpdateTicketService";`

e subistuimos

`return res.send();`

por

```
setTimeout(async () => {
await UpdateTicketService({ticketId: contactAndTicket.id,ticketData: { status: "closed" }});}, 1000);
//return res.send();
return res.send({ error: "SUCCESS" });
```

em UpdateTicketService ele cria o ticketData usando whatsappId, na sua versao nao tem esta variavel, atualizei todos os arquivo desse que tem referencia neste arquivo o sistema esta funcional mas nao realizar o fechamento do ticket, teria ideia do que pode ser ?

**Comment by rtenorioh** [comment]
Boa noite, acabei de fazer duas alterações no código e já implementei essa funcionabilidade, segue o commit:

https://github.com/rtenorioh/Press-Ticket/commit/e3301057774cc43eb9bfa0bef7e582217920b29b

**Comment by heenriquega** [comment]
muito obrigado!
