### ISSUE TITLE
Pesquisa de to ticket com erro

### ISSUE THREAD

**Issue by ADRIANOMAIRINCK** [rtenorioh/Press-Ticket#73]
Depois da atualizaçao - [Atualização do ListTicketService](https://github.com/rtenorioh/Press-Ticket/commit/6bbd2f071a4a8af9c2c6e132f1379538e7ecf3f7);

a pesquisa parou de funcionar

**Comment by rtenorioh** [comment]
Na realidade não sei informar em qual ponto deu o BO, porém a solução já esta em andamento, em breve solterei a correção

**Comment by gkp1** [comment]
Descobri o pq do erro amigo, é um bug bizarro do Sequelize, citei aqui:

https://github.com/rtenorioh/Press-Ticket/issues/87#issuecomment-1472632772

@ADRIANOMAIRINCK

**Comment by pflares** [comment]
ainda continua o erro
