### ISSUE TITLE
fila cinza (sem fila atribuida) somente para adm

### ISSUE THREAD

**Issue by heenriquega** [rtenorioh/Press-Ticket#8]
Ola, estou tentando fazer com que a fila cinza (sem fila atribuida) aparece apenas para adm, mas nao consegui ainda, fica como dica, caso finalize antes abro um pr.

**Comment by fernandesrobert** [comment]
Alguem sabe como eu posso definir o setor default para a conexão ?
aqui quando abro ticket não pega fila, isso é bastante ruim pois deixa a vista para todos os demais setores visualizarem e so é possivel corrigir o problema setando a fila manualmente no banco de dados.
