### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by fehveiga** [rtenorioh/Press-Ticket#85]
Ola pessoal, tudo bem?
Estou com uma duvida, consigo instalar esse sistema direto no meu site? Tipo hospedando os arquivos la ja...
Obrigado e boa noite.

**Comment by rtenorioh** [comment]
Boa noite, o Press Ticket precisa do Node JS para rodar, se a sua hospeagem ofecerer o Node JS pode ser que consiga
