### ISSUE TITLE
[MySql Error] Pesquisa de contatos retorna erro 

### ISSUE THREAD

**Issue by gkp1** [rtenorioh/Press-Ticket#87]

**Comment by jeffersondrosa** [comment]
Olá alguém sabe como corrigir a pesquisa.

**Comment by gkp1** [comment]
alterando a coluna pesquisada para "name" diz que a pesquisa é ambigua, nao to conseguindo entender muito bem o motivo.

![image](https://user-images.githubusercontent.com/63517877/224885389-3b11cfce-9d97-4f1b-bd12-be44b7e18966.png)

**Comment by gkp1** [comment]
> Olá alguém sabe como corrigir a pesquisa.

Creio que achei a solução, só vou poder testar mais tarde.


https://github.com/rtenorioh/Press-Ticket/blob/main/backend/src/services/TicketServices/ListTicketsService.ts#L48
mudar:
`      attributes: ["id", "name", "number", "profilePicUrl"],`
para:
`      attributes: ["id", ["name","contactname"], "number", "profilePicUrl"],`
Isso irá renomear a coluna name para contactname para desambiguar

https://github.com/rtenorioh/Press-Ticket/blob/main/backend/src/services/TicketServices/ListTicketsService.ts#L100
mudar `contact.name` para `contactname` porque definimos esse alias de coluna **contactname** acima

**Comment by gkp1** [comment]
"sqlMessage": "Unknown column 'contactname' in 'where clause'",
0|Press-Ticket-backend  |         "sql": "SELECT `Ticket`.*, `contact`.`id` AS `contact.id`, `contact`.`name` AS `contact.contactname`, `contact`.`number` AS `contact.number`, `contact`.`profilePicUrl` AS `contact.profilePicUrl`, `contact->extraInfo`.`id` AS `contact.extraInfo.id`, `contact->extraInfo`.`name` AS `contact.extraInfo.name`, `contact->extraInfo`.`value` AS `contact.extraInfo.value`, `contact->extraInfo`.`contactId` AS `contact.extraInfo.contactId`, `contact->extraInfo`.`createdAt` AS `contact.extraInfo.createdAt`, `contact->extraInfo`.`updatedAt` AS `contact.extraInfo.updatedAt`, `c

Honestamente já tentei umas 20 combinações de alias, não sempre me retorna query ambigua, e quando tento desambiguar diz que a coluna não existe. sendo que já chequei na DB e a tabela e colunas existem sim, com o nome correto "Contact(s)"

**Comment by gkp1** [comment]
@jeffersondrosa @rtenorioh fix para a pesquisa. Provavelmente esse fix precisa ser feito em outros campos de filtros como Tag, e no campo de quando voce clica em NOVO pra criar um ticket ...
Na linha 140, é só inserir **subQuery: false,** essa subQuery não tem utilidade neste caso e causa bug do sequelize quando utiliza include, limit e offset, e a documentação do sequelize por ser um lixo, não menciona isso. 

Onde inserir no codigo: linha 140 arquivo ListTicketService.ts https://github.com/rtenorioh/Press-Ticket/blob/main/backend/src/services/TicketServices/ListTicketsService.ts#L140
--------------------------------------------
(...)
 const { count, rows: tickets } = await Ticket.findAndCountAll({
    **subQuery: false,** 
    where: (.....)
