### ISSUE TITLE
Problemas no login

### ISSUE THREAD

**Issue by Mattbrndt** [rtenorioh/Press-Ticket#89]
Boa tarde,

Quando tento efetuar o login, estou encontrando uma tela de loading infinito e o seguinte output pelo Edge:

![image](https://user-images.githubusercontent.com/96841987/225110546-d2c9a4f7-9592-446c-99c0-452b2c7114b9.png)

Alguem consegue me dar uma luz?

**Comment by TsMuniz** [comment]
Esse problema esta na sua conexão com o banco de dados

**Comment by rtenorioh** [comment]
![image](https://user-images.githubusercontent.com/49109977/227747869-39869a72-38ad-46aa-898b-2098c3c98921.png)
como pode ver no print acima, os contantos estão sendo criados normalmente...

**Comment by gkp1** [comment]
> Boa tarde,
> 
> Quando tento efetuar o login, estou encontrando uma tela de loading infinito e o seguinte output pelo Edge:
> 
> ![image](https://user-images.githubusercontent.com/96841987/225110546-d2c9a4f7-9592-446c-99c0-452b2c7114b9.png)
> 
> Alguem consegue me dar uma luz?

Voce configurou algum **PORT**, algum **ENDEREÇO http ou https** (note o 's' adicional), no **.env frontend OU .env backend** OU nos **arquivos sites-enabled do NGINX**, incorretamente.
