### ISSUE TITLE
tag nao filtra

### ISSUE THREAD

**Issue by pflares** [rtenorioh/Press-Ticket#94]
ALGUEM SABE COMO CORRIGIR ESSE ERRO, EU MARCO O CLIENTE COM A TAG, MAS NAO FILTRA ELES QNDO MARCO ELA.

**Comment by gkp1** [comment]
no frontend, no ticketsmanager/index.js apesar de existir o state de selectedTickets, não há nenhum codigo que passa os selectedTickets para o component TicketsList atualizar.

Estou tentando corrigir

**Comment by codsec** [comment]
> no frontend, no ticketsmanager/index.js apesar de existir o state de selectedTickets, não há nenhum codigo que passa os selectedTickets para dentro do component TicketsList, para atualizar.
> 
> Estou tentando corrigir

Conseguiu?

**Comment by gkp1** [comment]
> > no frontend, no ticketsmanager/index.js apesar de existir o state de selectedTickets, não há nenhum codigo que passa os selectedTickets para dentro do component TicketsList, para atualizar.
> > Estou tentando corrigir
> 
> Conseguiu?

Estou meio sem tempo, assim que der atualizo aqui, o chatgpt ajuda bastante a debugar react.

**Comment by codsec** [comment]
> > > no frontend, no ticketsmanager/index.js apesar de existir o state de selectedTickets, não há nenhum codigo que passa os selectedTickets para dentro do component TicketsList, para atualizar.
> > > Estou tentando corrigir
> > 
> > 
> > Conseguiu?
> 
> Estou meio sem tempo, assim que der atualizo aqui, o chatgpt ajuda bastante a debugar react.

ok
